services:
  backend:
    image: fedoteh/pet-manager-api:latest
    # if the image can't be reached, builds the image
    # from the Dockerfile in the current directory.
    # Use `docker compose up --build` to force a local build 
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_PORT=5432
      - DB_NAME=${DB_NAME} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: npm start