name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js, version ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run npm ci
      run: npm ci

    - name: Install dependencies
      run: npm install && npm install --save-dev typescript
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker containers
      run: |
        docker-compose up -d
        docker-compose exec backend npm test

    - name: Shut down Docker containers
      if: always()
      run: docker-compose down
