name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # add more versions here if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set environment variables
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env.local
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env.local
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.local
        echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> .env.local
        echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> .env.local
        echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.local

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run Docker Compose
      run: docker compose --env-file .env.local -f docker-compose.yml up -d --build

    - name: Run tests
      run: docker compose exec backend npm test
